version: '3'

services:
  flaskapp:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - mysql
    environment:
      MYSQL_HOST: mysql
      MYSQL_DATABASE: flaskapp
      MYSQL_USER: root
      MYSQL_PASSWORD: YOUR_CONFIG
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: YOUR_CONFIG
      MYSQL_DATABASE: flaskapp
      MYSQL_USER: root
      MYSQL_PASSWORD: YOUR_CONFIG
